version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - php74
      - php81
      - php82
      - php83
  php:
    image: php:8.3-fpm
    volumes:
      - ./php:/var/www/html
      - ./nginx:/var/www/html/nginx
    environment:
      - PHP_VERSION=8.3
  php74:
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/html
      - ./nginx:/var/www/html/nginx
    environment:
      - PHP_VERSION=7.4
  php81:
    image: php:8.1-fpm
    volumes:
      - ./php:/var/www/html
      - ./nginx:/var/www/html/nginx
    environment:
      - PHP_VERSION=8.1
  php82:
    image: php:8.2-fpm
    volumes:
      - ./php:/var/www/html
      - ./nginx:/var/www/html/nginx
    environment:
      - PHP_VERSION=8.2
  php83:
    image: php:8.3-fpm
    volumes:
      - ./php:/var/www/html
      - ./nginx:/var/www/html/nginx
    environment:
      - PHP_VERSION=8.3
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xampp_db
      MYSQL_USER: xampp_user
      MYSQL_PASSWORD: xampp_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
